export enum AuthEvent {
  Auth = 'auth',
  SignIn = 'signIn',
  SignUp = 'signUp',
  SignOut = 'signOut',
  ConfirmSignUp = 'confirmSignUp',
  ConfirmSignIn = 'confirmSignIn',
  ForgotPassword = 'forgotPassword',
  ResetPassword = 'resetPassword',
  CognitoHostedUI = 'cognitoHostedUI',
  CustomChallenge = 'customChallenge',
  CustomAuth = 'customAuth',
  PfedAuth = 'pfedAuth',
  CognitoAuth = 'cognitoAuth',
  CognitoAuthError = 'cognitoAuthError',
  CognitoIdToken = 'cognitoIdToken',
  CognitoAccessToken = 'cognitoAccessToken',
  CognitoRefreshToken = 'cognitoRefreshToken',
  CognitoIdTokenExpired = 'cognitoIdTokenExpired',
  CognitoAccessTokenExpired = 'cognitoAccessTokenExpired',
  CognitoRefreshTokenExpired = 'cognitoRefreshTokenExpired',
  Token = 'token',
  Error = 'error',
  UserState = 'userState'
}
