export const COLOR_MODE = 'light'

export const RESOURCE_LIST_PAGE_SIZE = 10

export const DEFAULT_PAGE_SIZE = 8

export const ENDPOINT_AMS = process.env.NEXT_PUBLIC_ACCOUNT_MANAGEMENT_GRAPHQL_ENDPOINT

export const ENDPOINT_CMS = process.env.NEXT_PUBLIC_CONFIG_MANAGEMENT_GRAPHQL_ENDPOINT
